# Generated by Django 3.0.5 on 2020-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_description',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
