# Generated by Django 3.0.5 on 2020-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_place_place_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_description',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
