# Generated by Django 3.0.5 on 2020-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_auto_20200427_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
