# Generated by Django 3.0.5 on 2020-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='isActive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
