# Generated by Django 3.0.5 on 2020-05-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_mission_isactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
