# Generated by Django 3.0.5 on 2020-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_delete_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='isOccupied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
