# Generated by Django 3.0.5 on 2020-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_character_isoccupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
