# Generated by Django 3.0.5 on 2020-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0013_auto_20200506_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='strenght',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='agility_Ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='intelligence_Ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='strenght_Ratio',
            field=models.FloatField(default=1),
        ),
    ]
