# Generated by Django 3.0.5 on 2020-05-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0014_auto_20200506_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='strenght',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='strenght_Ratio',
            new_name='strength_Ratio',
        ),
    ]
