# Generated by Django 3.0.5 on 2020-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0017_auto_20200506_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='isOccupied',
        ),
        migrations.RemoveField(
            model_name='character',
            name='races',
        ),
        migrations.AddField(
            model_name='character',
            name='specie',
            field=models.CharField(choices=[('EL', 'Elf'), ('OR', 'Ork'), ('HU', 'Human')], default='HU', max_length=4),
        ),
    ]
