# Generated by Django 3.0.5 on 2020-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0018_auto_20200506_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
