# Generated by Django 3.0.5 on 2020-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0020_auto_20200506_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility_final',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_final',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_final',
            field=models.IntegerField(default=1),
        ),
    ]
