# Generated by Django 3.0.5 on 2020-05-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0023_auto_20200509_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='stat_Points',
            new_name='available_point',
        ),
    ]
