# Generated by Django 3.0.6 on 2020-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0025_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character_number_max',
            field=models.IntegerField(default=3),
        ),
    ]
