# Generated by Django 3.0.6 on 2020-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0026_profile_character_number_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
