# Generated by Django 3.0.6 on 2020-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0027_character_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
