# Generated by Django 3.0.6 on 2020-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0028_auto_20200518_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(),
        ),
    ]
