# Generated by Django 3.0.6 on 2020-05-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0029_auto_20200518_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(default='F', max_length=3),
        ),
    ]
