# Generated by Django 3.0.6 on 2020-05-20 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0033_remove_character_finishtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='finishtime',
            field=models.DateField(default=datetime.datetime(2020, 5, 20, 23, 39, 11, 309835)),
        ),
    ]
