# Generated by Django 3.0.6 on 2020-05-20 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0034_character_finishtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='agility_final',
        ),
        migrations.RemoveField(
            model_name='character',
            name='finishtime',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence_final',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength_final',
        ),
        migrations.AddField(
            model_name='character',
            name='finishTime',
            field=models.DateField(default=datetime.datetime(2020, 5, 20, 23, 55, 33, 528600)),
        ),
    ]
