# Generated by Django 3.0.6 on 2020-05-20 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0039_auto_20200521_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 27, 19, 559606, tzinfo=utc)),
        ),
    ]
