# Generated by Django 3.0.6 on 2020-05-22 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0040_auto_20200521_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 4, 0, 22, 259116, tzinfo=utc)),
        ),
    ]
