# Generated by Django 3.0.6 on 2020-05-22 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0041_auto_20200522_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 4, 43, 41, 279714, tzinfo=utc)),
        ),
    ]
