# Generated by Django 3.0.6 on 2020-05-22 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0042_auto_20200522_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='max_Hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 4, 53, 9, 412476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(default=1),
        ),
    ]
