# Generated by Django 3.0.6 on 2020-05-22 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0043_auto_20200522_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 5, 10, 21, 823993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='specie',
            field=models.CharField(choices=[('Spider', 'Spd'), ('Insectoid', 'Ins'), ('Rhinoceros', 'Rhi'), ('Canine', 'Dog'), ('Feline', 'Cat'), ('Ursidae', 'Bear'), ('Human', 'Human')], default='Human', max_length=10),
        ),
    ]
