# Generated by Django 3.0.6 on 2020-05-22 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0045_auto_20200522_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='evolution_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 5, 25, 48, 364005, tzinfo=utc)),
        ),
    ]
