# Generated by Django 3.0.6 on 2020-05-22 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0047_auto_20200522_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='can_Evolve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 14, 29, 57, 823686, tzinfo=utc)),
        ),
    ]
