# Generated by Django 3.0.6 on 2020-05-22 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0048_auto_20200522_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='damage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 18, 1, 792545, tzinfo=utc)),
        ),
    ]
