# Generated by Django 3.0.6 on 2020-05-23 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0049_auto_20200522_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='isAlive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='respawnDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 15, 0, 43, 987593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 15, 0, 43, 987593, tzinfo=utc)),
        ),
    ]
