# Generated by Django 3.0.6 on 2020-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0054_auto_20200602_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(choices=[('Spider', 'Spider'), ('Insectoid', 'Insectoid'), ('Rhinoceros', 'Rhinoceros'), ('Canine', 'Canine'), ('Feline', 'Feline'), ('Ursidae', 'Ursidae')], default='Rhinoceros', max_length=25),
        ),
    ]
